### ISSUE TITLE
Using a Dial Gauge for negative values

### ISSUE THREAD

**Issue by mjs513** [KrisKasprzak/GraphingFunction#2]
Hi Chris
Is it possible to use a dial to plot values from say -200 to +200.  I gave it a try and yes it does display the range no issue but when I go negative it jumps either to a fixed negative value or points straight down.  And yes positive values work no issue.  Or am I just doing something wrong.

Thanks
Mike

**Comment by KrisKasprzak** [comment]
I'll take a look
Thanks,
Kris  

    On Wednesday, December 22, 2021, 09:11:25 AM CST, Mike S ***@***.***> wrote:  
 
 


Hi Chris
Is it possible to use a dial to plot values from say -200 to +200. I gave it a try and yes it does display the range no issue but when I go negative it jumps either to a fixed negative value or points straight down. And yes positive values work no issue. Or am I just doing something wrong.

Thanks
Mike

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mjs513** [comment]
Been doing more testing seems to work if I put a negagtive value in for volts in the dial example but not working correctly in may app.  Think it might be my values are uint32's ?

**Comment by mjs513** [comment]
Oh Shoot - just noticed I put this issue in the wrong repository,  Will close it and reissue it in the right spot.

**Comment by KrisKasprzak** [comment]
what data type are you using for the draw method?
I just tested this call, and i can plot negative values// bVolts is a float
 Volts.draw(bVolts - 4.0);



Thanks,
Kris ***@***.***
 

    On Wednesday, December 22, 2021, 09:28:53 AM CST, Mike S ***@***.***> wrote:  
 
 


Been doing more testing seems to work if I put a negagtive value in for volts in the dial example but not working correctly in may app. Think it might be my values are uint32's ?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mjs513** [comment]
Just posted in the other repository.  Yep did the same thing and I retested converting the unit32 to float<
bVolts = (float) value

**Comment by mjs513** [comment]
Ok got it fixed - turns out I did a copy and paste and what I copied was wrong.  As soon as I typed the above I figure it out.  

what I was doing is taking Quad encoder data from the T4 and using dials to display it - now it working.  I got tired of looking at raw data :)

**Comment by mjs513** [comment]
Thanks for listening to me rant :)
